variable "ami" {}
variable "access_key" {}
variable "secret_key" {}
variable "git_token" {}
variable "ssh_user" {}
variable "privet_key" {}
variable "auth" {}
variable "aws_region" {}
variable "aws_AZ1" {}
variable "private_key_path" {}
